name: "build react project"
run-name: "building react project"
on: [push]
# defaults:
#     run:
#      working-directory: ./front
jobs:
  Build-React-App:
    runs-on: ubuntu-latest
    steps:
        - run: ls
        - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
        - name: "checkout"
          uses: actions/checkout@v4
        - run: npm install
        - name: "build"
          run: npm run build
        - name: "deploy"
          uses: JamesIves/github-pages-deploy-action@4.1.1
          with:
            branch: gh-pages
            folder: front/build
