name: "build react project"
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push]
jobs:
  Build-React-App:
    runs-on: ubuntu-latest
    steps:
        - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
        - name: "checkout"
          uses: actions/checkout@v4
        - run: |
            cd front
            npm install
            npm run build
        - name: "deploy"
          uses: JamesIves/github-pages-deploy-action@4.1.1
          with:
            branch: gh-pages
            folder: front/build